spring:
  application:
    name: SmartVan

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/smartvan}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Password123!}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
